# Generated by Django 3.2.9 on 2021-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_exam_name', models.CharField(max_length=8)),
                ('full_exam_name', models.CharField(max_length=32)),
                ('institution_name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=64)),
                ('passing_year', models.IntegerField()),
                ('board', models.CharField(max_length=4)),
                ('result', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_list', models.CharField(max_length=100)),
                ('hobby_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=16, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=48, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=48, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True, max_length=256, null=True)),
                ('permanent_address', models.TextField(blank=True, max_length=256, null=True)),
                ('religion', models.CharField(blank=True, max_length=16, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=16, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=4, null=True)),
                ('nationality', models.CharField(blank=True, max_length=24, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('nid', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_certificate_no', models.CharField(blank=True, max_length=32, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_image', models.ImageField(blank=True, default='images/profile_picture/Default.jpg', null=True, upload_to='images/profile_picture/')),
            ],
            options={
                'verbose_name_plural': 'Personal Info',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(max_length=30)),
                ('team_member_occupation', models.CharField(max_length=20)),
                ('team_member_experties', models.CharField(max_length=200)),
                ('team_member_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
