# Generated by Django 3.2.9 on 2021-12-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='hobby',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
