# Generated by Django 3.2.9 on 2021-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20211212_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_exam_name', models.CharField(max_length=8)),
                ('fll_exam_name', models.CharField(max_length=32)),
                ('institution_name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=64)),
                ('passing_year', models.IntegerField()),
                ('board', models.CharField(max_length=4)),
                ('result', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_list', models.CharField(blank=True, max_length=100, null=True)),
                ('hobby_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hobby',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=50, null=True)),
                ('service_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(blank=True, max_length=30, null=True)),
                ('team_member_occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('team_member_experties', models.CharField(blank=True, max_length=200, null=True)),
                ('team_member_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
