# Generated by Django 3.2.9 on 2021-12-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_education_hobby_service_skills_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='personal_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.personal_info'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='personal_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.personal_info'),
        ),
        migrations.AddField(
            model_name='service',
            name='personal_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.personal_info'),
        ),
        migrations.AddField(
            model_name='skills',
            name='personal_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.personal_info'),
        ),
        migrations.AddField(
            model_name='team',
            name='personal_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myportfolio.personal_info'),
        ),
    ]
