# Generated by Django 3.2.9 on 2021-12-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_auto_20211212_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='fll_exam_name',
            new_name='full_exam_name',
        ),
    ]
