# Generated by Django 3.2.9 on 2021-12-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_team_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_picture/Default.jpg', null=True, upload_to='images/profile_picture/'),
        ),
    ]
